language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7-dev
before_install:
- pip install pytest pytest-cov
- pip install coveralls
script:
- pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
    python: 3.7-dev
  password:
    secure: TykYIKba2EwOzb7HNQdoOaqfs+utILD5ryf/3WktF6KJ5IDKYcAarDWlt1ykUfPkXri6QlGXZF+t5KeISP7sd3+V0RrDXcT3zpBr0zNkHZykKLbBGLLOnKrA9rEvdnWOJSxV/A9L+WbGYdD2QUItJQo6rKLB+VSegPE704PMBY6GkJ56FhLaLvzbvleOOJPw6f1OuSXahuLPAPKL285A4BweBra4UEqCDYOeDqa3ONKVSTsVru+V/NzgrlvA8RAvizAh/9Ev0blRFIaIyw0pdOuOhsba7r362ABDF0QnH7ix9olwbtg7X7dDXaHXqi8KkNM6l4iqkP2G1tXG9Xyc/IjoRVtNQrTaJGNwScTLexwzx6ZUNbaYvkmYwPE+EItWhuuXydlZfrvk4xmmnol74UCmxuxWDIj+7zNNWsofbanUve50UMaS/zrF7VZWWPj4ba7Xq+P9wK4pv5VWkjGpqlRQlp6aWpzhLIR39i3U/M+xdMZikNvigFttgcAFeOzkPtLPBPk7orhOmPK+rLeC9+ESc5/Bn4LFp7es/JUJmD3i1hwICDM14640rMNcDiPfgTou5luwbQAjoHsl+x7Hn/z5DXJFxNKv8VDfO6q3tWo0IMcLFf4nGTctcfJhZRoFP+V0xWtfsW4fRNoyLBLLyTpa/YAtCJl+MzLboANDOPg=
