language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7-dev
before_install:
- pip install pytest pytest-cov
- pip install coveralls
script:
- pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
    python: 3.7-dev
